### ISSUE TITLE
angular-localization does not work with Angular 1.6.2

### ISSUE THREAD

**Issue by peter-martinez-62** [doshprompt/angular-localization#110]
code is using promise.success() instead of promise..then()

here is the error:
TypeError: c.get(...).success is not a function
    at p (http://localhost:9002/bower_components/angular-localization/angular-localization.min.js:8:1270)
    at q (http://localhost:9002/bower_components/angular-localization/angular-localization.min.js:8:1637)
    at http://localhost:9002/bower_components/angular-localization/angular-localization.min.js:8:1872
    at Array.forEach (native)
    at Object.r [as ready] (http://localhost:9002/bower_components/angular-localization/angular-localization.min.js:8:1845)

**Comment by andrewsmalek** [comment]
you just need to use the latest Angular-Localization v1.6 which supports the new .then() instead of .success()
you may now download it from here until it got released officially : https://drive.google.com/file/d/0B6ppbyCzTs4tOUpPSUhWYTZTVmc/view?usp=sharing

**Comment by SDries** [comment]
@andrewsaad, your link doesn't work for me.
Do you have an alternative source?
Do you have an idea when angular-localization will support 1.6?

Thank you

**Comment by andrewsmalek** [comment]
Angular-localization do support angular V1.6, but only the source code has the updates, not the distributed one yet, however.. I've updated the url for v1.6, it's working now.

**Comment by Carnid** [comment]
I have made a fork [here](https://github.com/Spiria-Digital/angular-localization)
It incorporates the latest changes to work with 1.6. It also adds a feature for nested json language files.
You can install it via bower using `bower install angular-localization-spiria --save`
Let me know if there are any [issues](https://github.com/Spiria-Digital/angular-localization/issues).

**Comment by YegorDia** [comment]
Thanks Carnid!
